# Generated by Django 6.0.1 on 2026-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('emission_factor_kg_co2_per_kg', models.FloatField()),
                ('biodegradable', models.BooleanField(default=False)),
                ('manufacturing_intensity', models.CharField(choices=[('LOW', 'Low Intensity'), ('MEDIUM', 'Medium Intensity'), ('HIGH', 'High Intensity')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Material Factors',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=100)),
                ('weight_kg', models.FloatField()),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road'), ('RAIL', 'Rail')], max_length=20)),
                ('transport_distance_km', models.FloatField()),
                ('predicted_co2_kg', models.FloatField()),
                ('material_co2', models.FloatField(blank=True, null=True)),
                ('manufacturing_co2', models.FloatField(blank=True, null=True)),
                ('transport_co2', models.FloatField(blank=True, null=True)),
                ('trees_to_offset', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
