# Generated by Django 5.0.1 on 2026-06-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=300, unique=True)),
                ('source_type', models.CharField(choices=[('PDF', 'PDF'), ('MARKDOWN', 'Markdown'), ('TEXT', 'Plain Text'), ('URL', 'Web URL')], default='TEXT', max_length=20)),
                ('citation', models.CharField(blank=True, help_text="Human-readable citation, e.g. 'IPCC AR6 WGIII Ch.7'", max_length=500)),
                ('num_chunks', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('retrieved_sources', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisor.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
